export const IS_LOADING = "IS_LOADING";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_MOVEMENT_LIST = "GET_MOVEMENT_LIST";
export const GET_MOVEMENT_DETAILS = "GET_MOVEMENT_DETAILS";
export const GET_MOVEMENT_ID = "GET_MOVEMENT_ID";
export const GET_VEHICLE_DATA = "GET_VEHICLE_DATA";
export const GET_AGENCIES_DATA = "GET_AGENCIES_DATA";
export const GET_PILOT_DATA = "GET_PILOT_DATA";
export const GET_PILOT_DETAILS_DATA = "GET_PILOT_DETAILS_DATA";
export const GET_AGENCIES_DETAILS_DATA = "GET_AGENCIES_DETAILS_DATA";
export const SET_CURRENT_USER_DETAILS = "SET_CURRENT_USER_DETAILS";
export const SET_CURRENT_LOCATION_INFO = "SET_CURRENT_LOCATION_INFO";
export const DELETE_MOVEMENTS_ID = "DELETE_MOVEMENTS_ID";

export const SET_DARK_THEME = "SET_DARK_THEME";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
